---
- name: Configure global settings.
  lineinfile:
    dest: "{{ edb_config_path }}/postgresql.conf"
    regexp: "^#?{{ item.option }}.+$"
    line: "{{ item.option }} = '{{ item.value }}'"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ edb_global_config_options }}"
  notify: restart edb

- name: Configure host based authentication (if entries are configured).
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ edb_config_path }}/pg_hba.conf"
    owner: "{{ edb_user }}"
    group: "{{ edb_group }}"
    mode: 0600
  notify: restart edb
  when: edb_hba_entries | length > 0

- name: Ensure EDB unix socket dirs exist.
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ edb_user }}"
    group: "{{ edb_group }}"
    mode: "{{ edb_unix_socket_directories_mode }}"
  with_items: "{{ edb_unix_socket_directories }}"
