---
- name: Set EDB environment variables.
  template:
    src: edb.sh.j2
    dest: /etc/profile.d/edb.sh
    mode: 0644
  notify: restart edb

- name: Ensure EDB data directory exists.
  file:
    path: "{{ edb_data_dir }}"
    owner: "{{ edb_user }}"
    group: "{{ edb_group }}"
    state: directory
    mode: 0700

- name: Check if EDB database is initialized.
  stat:
    path: "{{ edb_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: Ensure EDB database is initialized.
  command: "{{ edb_bin_path }}/initdb -D {{ edb_data_dir }}"
  when: not pgdata_dir_version.stat.exists
  become: true
  become_user: "{{ edb_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
