---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: initialize.yml
- include_tasks: configure.yml

- name: Ensure EDB is started and enabled on boot.
  service:
    name: "{{ edb_daemon }}"
    state: "{{ edb_service_state }}"
    enabled: "{{ edb_service_enabled }}"

# Configure EDB.
- import_tasks: users.yml
- import_tasks: databases.yml
