---
- name: Set up apt sources.list.d.
  template:
    src: edb-repo.list.j2
    dest: /etc/apt/sources.list.d/edb-repo.list

- name: Add the EDB signing key.
  apt_key:
    url: https://apt.enterprisedb.com/edb-deb.gpg.key
    state: present

- name: Update apt
  apt:
    update_cache: true
  changed_when: false

- name: Ensure EDB Python libraries are installed.
  apt:
    name: "{{ edb_python_library }}"
    state: present

- name: Ensure EDB packages are installed.
  apt:
    name: "{{ edb_packages }}"
    state: present

- name: Ensure all configured locales are present.
  locale_gen: "name={{ item }} state=present"
  with_items: "{{ edb_locales }}"
  register: locale_gen_result

- name: Force-restart EDB after new locales are generated.
  service:
    name: "{{ edb_daemon }}"
    state: restarted
  when: locale_gen_result.changed
