---
- name: Ensure EDB users are present.
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
    db: "{{ item.db | default(edb_default_db) }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default(edb_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(edb_unix_socket_directories[0]) }}"
    port: "{{ item.port | default(5444) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ edb_users }}"
  no_log: "{{ edb_users_no_log }}"
  become: true
  become_user: "{{ edb_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
