---
# Variable configuration.
- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Include OS-specific variables (RedHat).
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:
  - ansible_os_family == 'RedHat'
  - ansible_distribution != 'Fedora'

- name: Include OS-specific variables (Fedora).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'Fedora'

- name: Define edb_packages.
  set_fact:
    edb_packages: "{{ __edb_packages | list }}"
  when: edb_packages is not defined

- name: Define edb_version.
  set_fact:
    edb_version: "{{ __edb_version }}"
  when: edb_version is not defined

- name: Define edb_daemon.
  set_fact:
    edb_daemon: "{{ __edb_daemon }}"
  when: edb_daemon is not defined

- name: Define edb_data_dir.
  set_fact:
    edb_data_dir: "{{ __edb_data_dir }}"
  when: edb_data_dir is not defined

- name: Define edb_bin_path.
  set_fact:
    edb_bin_path: "{{ __edb_bin_path }}"
  when: edb_bin_path is not defined

- name: Define edb_config_path.
  set_fact:
    edb_config_path: "{{ __edb_config_path }}"
  when: edb_config_path is not defined

- name: Define edb_unix_socket_directories_mode.
  set_fact:
    edb_unix_socket_directories_mode: >-
      {{ __edb_unix_socket_directories_mode | default('02775') }}
  when: edb_unix_socket_directories_mode is not defined
