---
- name: Converge
  hosts: all
  become: true

  vars:
    edb_users_no_log: false
    edb_databases:
      - name: example
    edb_users:
      - name: jdoe

  pre_tasks:
    - name: Set custom variables for old CentOS 6 EDB install.
      set_fact:
        edb_hba_entries: []
        edb_global_config_options:
          - option: unix_socket_directory
            value: "{{ edb_unix_socket_directories[0] }}"
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_version.split('.')[0] == '6'

  tasks:
    - include_vars:
        file: repo-creds.yml
    - import_role:
        name: terradatum.edb

  post_tasks:
    - name: Verify edb is running.
      command: "{{ edb_bin_path }}/pg_ctl -D {{ edb_data_dir }} status"
      changed_when: false
      become: true
      become_user: enterprisedb
