---
- name: Converge
  hosts: all
  become: true

  vars:
    edb_users_no_log: false
    edb_databases:
      - name: example
    edb_users:
      - name: jdoe

  pre_tasks:
    - name: Setup EPEL.
      include_role:
        name: geerlingguy.repo-epel
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

    - name: RedHat
      block:
        - name: Update yum.
          yum:
            update_cache: true
          changed_when: false

        - name: Install gnupg2.
          yum:
            name: gnupg2
            state: present

      when: ansible_os_family == 'RedHat'

    - name: Debian
      block:
        - name: Update apt.
          apt:
            update_cache: true
            cache_valid_time: 86400
          changed_when: false

        - name: Install gpg-agent.
          apt:
            name:
              - gpg-agent
              - apt-transport-https
            state: present
          when:
            - ( ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= '18') or
              ( ansible_distribution == 'Debian' and ansible_distribution_major_version >= '8')

        - name: Install gpg-agent.
          apt:
            name:
              - gnupg-agent
              - apt-transport-https
            state: present
          when:
            - ( ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '16') or
              ( ansible_distribution == 'Debian' and ansible_distribution_major_version == '7')

      when: ansible_os_family == 'Debian'

    # The Fedora 30+ container images have only C.UTF-8 installed
    - name: Set database locale if using Fedora 30+ or RedHat 8+.
      set_fact:
        edb_databases:
          - name: example
            lc_collate: "C.UTF-8"
            lc_ctype: "C.UTF-8"
      when:
        - ( ansible_distribution == 'Fedora' and ansible_distribution_major_version >= '30') or
          ( ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8')

    - name: Set custom variables for old CentOS 6 EDB install.
      set_fact:
        edb_hba_entries: []
        edb_global_config_options:
          - option: unix_socket_directory
            value: "{{ edb_unix_socket_directories[0] }}"
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_version.split('.')[0] == '6'

  tasks:
    - include_vars:
        file: repo-creds.yml
    - import_role:
        name: terradatum.edb

  post_tasks:
    - name: Verify edb is running.
      command: "{{ edb_bin_path }}/pg_ctl -D {{ edb_data_dir }} status"
      changed_when: false
      become: true
      become_user: enterprisedb
