name: Ansible Role for EnterpriseDB Advanced Server (EPAS)
on:
  push:
    branches:
      - master

env:
  ROLE_NAME: edb

jobs:
  ansible:
    runs-on: [ubuntu-latest]
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      fail-fast: true
      matrix:
        molecule_distro: [centos7, centos8, fedora31, ubuntu2004, ubuntu1804, debian10]
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: terradatum.edb
      - name: install tree
        run: sudo apt-get install -y tree
      - name: Debug the directory
        run: tree
      - name: Set up repo creds
        env:
          REPO_CREDS: ${{ secrets.REPO_CREDS }}
        run: echo "$REPO_CREDS" > ./molecule/default/repo-creds.yml
      - name: Install test dependencies
        run: pip install molecule yamllint ansible-lint docker
      - name: Run tests
        env:
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
        run: molecule test
