name: Ansible Role for EnterpriseDB Advanced Server (EPAS)
on:
  push:
    branches:
      - master

env:
  ROLE_NAME: edb

jobs:
  ansible:
    runs-on: [ubuntu-latest]
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
        working-directory: terradatum.edb
    strategy:
      fail-fast: true
      matrix:
        molecule_distro: [centos7, centos8, fedora31, ubuntu2004, ubuntu1804, debian10]
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: terradatum.edb
      - name: Set up miniconda environment
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          channels: conda-forge
          activate-environment: conda-env
      - name: Set up repo creds
        env:
          REPO_CREDS: ${{ secrets.REPO_CREDS }}
        run: 'echo -n "$REPO_CREDS" > molecule/default/repo-creds.yml'
      - name: Install test dependencies
        run: conda install -y molecule yamllint ansible-lint docker-py click-help-colors
      - name: Run tests
        env:
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
        run: molecule test
